version: '3'

services:

  php-apache:
    container_name: php-apache
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    links:
     - mysql

  mysql:
    container_name: database
    image: mysql:8.0
    restart: always
    ports:
      - '9906:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    volumes:
     - ./dump/docker-php.sql:/docker-entrypoint-initdb.d/docker-php.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql